export enum TraitNames {
  SEED_COVERING = 'Seed Covering',
  BRANCHING = 'Branching',
  STEM_FOCUS = 'Stem Focus',
  SEED_SIZE = 'Seed Cluster Size',
  TEMP_TOLERANCE = 'Temperature Tolerance',
  MOIS_TOLERANCE = 'Moisture Tolerance',
  GROWTH_SPEED = 'Growth Speed',
  NITROGEN_REQ = 'Nitrogen Requirement',
  TOUGHNESS = 'Toughness',
  STEM_HEIGHT = 'Stem Height',
  SEEDS_ON_TOP = 'Seeds On Top',
  SWEETNESS = 'Sweetness',
  STARCH = 'Starch',
  PROTEIN = 'Protein',
  BITTERNESS = 'Bitterness',
  SOURNESS = 'Sourness',
  SPICINESS = 'Spiciness',
  TOXICITY = 'Toxicity'
}
