// grab the mongoose module
var mongoose = require('mongoose');

// define our plant model
module.exports = mongoose.model('Plant', {
	plantID : {type : Number, default: null},
	family : {type : String, default: ''},
	adjective : {type : String, default: ''},
	specName : {type: String, default: ''},
	sireID : {type: Number, default: null},
	state : {type: Number, default: null},
	progress : {type: Number, default: null},
	numSeeds : {type: Number, default: null},
	numPollen : {type: Number, default: null},
	numCuttings : {type: Number, default: null},
	TI1 : {type: [Boolean], default: null},
	TI2 : {type: [Boolean], default: null},
	TI3 : {type: [Boolean], default: null},
	MIV : {type: [Boolean], default: null},
	MM1 : {type: [Boolean], default: null},
	MM2 : {type: [Boolean], default: null},
	PER : {type: [Boolean], default: null},
	CFX : {type: [Boolean], default: null},
	RCH : {type: [Boolean], default: null},
	MOI : {type: [Boolean], default: null},
	TEM : {type: [Boolean], default: null},
	PST : {type: [Boolean], default: null},
	SZ1 : {type: [Boolean], default: null},
	SZ2 : {type: [Boolean], default: null},
	QT1 : {type: [Boolean], default: null},
	QT2 : {type: [Boolean], default: null},
	PS1 : {type: [Boolean], default: null},
	PS2 : {type: [Boolean], default: null},
	TOF : {type: [Boolean], default: null},
	DFS : {type: [Boolean], default: null},
	DCP : {type: [Boolean], default: null},
	PRT : {type: [Boolean], default: null},
	VIT : {type: [Boolean], default: null},
	FL1 : {type: [Boolean], default: null},
	FL2 : {type: [Boolean], default: null},
	FL3 : {type: [Boolean], default: null},
	CL1 : {type: [Boolean], default: null},
	CL2 : {type: [Boolean], default: null},
	CL3 : {type: [Boolean], default: null}
});